repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        args: [--prose-wrap, always, --print-width, "80"]
        types: [markdown]
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-tidy
        args: ["-p=builddir", "--warnings-as-errors=*"]
-   repo: local
    hooks:
    -   id: format
        name: format
        entry: ./scripts/format.sh
        language: script
        pass_filenames: false
        files: \.(c|h)$
