repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        args: [--prose-wrap, always, --print-width, "80"]
        types: [markdown]
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-tidy
        args: ["-p=builddir", "--warnings-as-errors=*"]
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|h)$
    -   id: meson-test
        name: Meson Test
        entry: meson test -C builddir --no-suite integration
        language: system
        pass_filenames: false
        files: \.(c|h)$
    -   id: integration-test
        name: Integration Test
        entry: meson test -C builddir --suite integration --verbose
        language: system
        pass_filenames: false
        files: \.(c|h|py|sh)$
    -   id: integration-test-clang
        name: Integration Test (Clang)
        entry: >-
          bash -c 'if [ ! -d builddir_clang ]; then
          CC=clang meson setup builddir_clang; fi &&
          meson test -C builddir_clang --suite integration --verbose'
        language: system
        pass_filenames: false
        files: \.(c|h|py|sh)$
