name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgumbo-dev libfuse3-dev libssl-dev \
            libcurl4-openssl-dev uuid-dev help2man libexpat1-dev pkg-config \
            meson ninja-build astyle clang-tidy
      - name: Set up build directory
        run: |
          meson setup builddir
      - uses: pre-commit/action@v3.0.1
